In [5]:
import numpy as np 
import pandas as pd

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

x_train = train_data.drop(['Survived'], axis = 1)
y_train = train_data['Survived']

x_test = test_data
y_test = pd.DataFrame()



In [6]:
x_train["Age"].describe()


count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [7]:
features = ['Pclass', 'Sex', 'SibSp', 'Parch']

x_train = pd.get_dummies(train_data[features])
x_test = pd.get_dummies(test_data[features])

# Random Forest

In [77]:
from sklearn.ensemble import RandomForestClassifier

modelRF = RandomForestClassifier(n_estimators = 100, max_depth = 5)

modelRF.fit(x_train,y_train)


RandomForestClassifier(max_depth=5)

In [78]:
predictions = modelRF.predict(x_test)
predictions

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [79]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")
#0.77272 score


Your submission was successfully saved!


# Gradient Boosting Classifier

In [82]:
from sklearn.ensemble import GradientBoostingClassifier

modelGBC = GradientBoostingClassifier()
modelGBC.fit(x_train, y_train)


array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

# CatBoost

In [21]:
from catboost import CatBoostClassifier

x_train_cat = train_data[features + ["Age"]]
y_train_cat = train_data["Survived"]

x_test_cat = test_data[features + ["Age"]]

modelCatBoost = CatBoostClassifier(cat_features = features)

modelCatBoost.fit(x_train_cat,y_train_cat)

Learning rate set to 0.009807
0:	learn: 0.6866466	total: 18.3ms	remaining: 18.3s
1:	learn: 0.6812456	total: 28.8ms	remaining: 14.4s
2:	learn: 0.6760542	total: 42.1ms	remaining: 14s
3:	learn: 0.6709017	total: 52.2ms	remaining: 13s
4:	learn: 0.6657461	total: 65.6ms	remaining: 13.1s
5:	learn: 0.6608563	total: 79.2ms	remaining: 13.1s
6:	learn: 0.6558757	total: 95.2ms	remaining: 13.5s
7:	learn: 0.6511036	total: 108ms	remaining: 13.4s
8:	learn: 0.6463669	total: 125ms	remaining: 13.8s
9:	learn: 0.6419020	total: 136ms	remaining: 13.4s
10:	learn: 0.6375900	total: 146ms	remaining: 13.1s
11:	learn: 0.6333337	total: 156ms	remaining: 12.8s
12:	learn: 0.6290322	total: 169ms	remaining: 12.8s
13:	learn: 0.6246269	total: 188ms	remaining: 13.2s
14:	learn: 0.6198677	total: 208ms	remaining: 13.7s
15:	learn: 0.6154667	total: 227ms	remaining: 14s
16:	learn: 0.6112504	total: 247ms	remaining: 14.3s
17:	learn: 0.6075828	total: 260ms	remaining: 14.2s
18:	learn: 0.6039305	total: 276ms	remaining: 14.3s
19:	learn:

168:	learn: 0.4188989	total: 2.99s	remaining: 14.7s
169:	learn: 0.4185416	total: 3.01s	remaining: 14.7s
170:	learn: 0.4182261	total: 3.03s	remaining: 14.7s
171:	learn: 0.4179159	total: 3.05s	remaining: 14.7s
172:	learn: 0.4178728	total: 3.06s	remaining: 14.6s
173:	learn: 0.4177332	total: 3.07s	remaining: 14.6s
174:	learn: 0.4175584	total: 3.09s	remaining: 14.6s
175:	learn: 0.4172448	total: 3.11s	remaining: 14.6s
176:	learn: 0.4165531	total: 3.14s	remaining: 14.6s
177:	learn: 0.4161481	total: 3.16s	remaining: 14.6s
178:	learn: 0.4157238	total: 3.17s	remaining: 14.6s
179:	learn: 0.4154223	total: 3.19s	remaining: 14.6s
180:	learn: 0.4147825	total: 3.21s	remaining: 14.5s
181:	learn: 0.4146704	total: 3.23s	remaining: 14.5s
182:	learn: 0.4144154	total: 3.25s	remaining: 14.5s
183:	learn: 0.4141882	total: 3.27s	remaining: 14.5s
184:	learn: 0.4137144	total: 3.28s	remaining: 14.5s
185:	learn: 0.4132795	total: 3.3s	remaining: 14.5s
186:	learn: 0.4130083	total: 3.32s	remaining: 14.4s
187:	learn: 0

329:	learn: 0.3868460	total: 5.79s	remaining: 11.8s
330:	learn: 0.3867561	total: 5.81s	remaining: 11.7s
331:	learn: 0.3865683	total: 5.83s	remaining: 11.7s
332:	learn: 0.3865390	total: 5.84s	remaining: 11.7s
333:	learn: 0.3863928	total: 5.86s	remaining: 11.7s
334:	learn: 0.3862580	total: 5.88s	remaining: 11.7s
335:	learn: 0.3861035	total: 5.9s	remaining: 11.7s
336:	learn: 0.3858413	total: 5.92s	remaining: 11.7s
337:	learn: 0.3857206	total: 5.94s	remaining: 11.6s
338:	learn: 0.3856480	total: 5.96s	remaining: 11.6s
339:	learn: 0.3855727	total: 5.98s	remaining: 11.6s
340:	learn: 0.3855614	total: 5.99s	remaining: 11.6s
341:	learn: 0.3852005	total: 6.01s	remaining: 11.6s
342:	learn: 0.3851302	total: 6.03s	remaining: 11.6s
343:	learn: 0.3850740	total: 6.05s	remaining: 11.5s
344:	learn: 0.3849663	total: 6.07s	remaining: 11.5s
345:	learn: 0.3848398	total: 6.09s	remaining: 11.5s
346:	learn: 0.3847450	total: 6.11s	remaining: 11.5s
347:	learn: 0.3845666	total: 6.13s	remaining: 11.5s
348:	learn: 0

492:	learn: 0.3686767	total: 8.62s	remaining: 8.86s
493:	learn: 0.3685339	total: 8.64s	remaining: 8.85s
494:	learn: 0.3684940	total: 8.65s	remaining: 8.83s
495:	learn: 0.3684853	total: 8.66s	remaining: 8.8s
496:	learn: 0.3683671	total: 8.68s	remaining: 8.79s
497:	learn: 0.3683184	total: 8.7s	remaining: 8.77s
498:	learn: 0.3681807	total: 8.72s	remaining: 8.76s
499:	learn: 0.3681089	total: 8.74s	remaining: 8.74s
500:	learn: 0.3680337	total: 8.76s	remaining: 8.72s
501:	learn: 0.3679850	total: 8.78s	remaining: 8.71s
502:	learn: 0.3679767	total: 8.79s	remaining: 8.68s
503:	learn: 0.3678909	total: 8.8s	remaining: 8.66s
504:	learn: 0.3677986	total: 8.82s	remaining: 8.65s
505:	learn: 0.3677108	total: 8.84s	remaining: 8.63s
506:	learn: 0.3676982	total: 8.85s	remaining: 8.61s
507:	learn: 0.3675725	total: 8.87s	remaining: 8.59s
508:	learn: 0.3674702	total: 8.89s	remaining: 8.58s
509:	learn: 0.3674081	total: 8.91s	remaining: 8.56s
510:	learn: 0.3673753	total: 8.92s	remaining: 8.54s
511:	learn: 0.3

660:	learn: 0.3564043	total: 11.5s	remaining: 5.87s
661:	learn: 0.3563653	total: 11.5s	remaining: 5.86s
662:	learn: 0.3562613	total: 11.5s	remaining: 5.84s
663:	learn: 0.3560931	total: 11.5s	remaining: 5.83s
664:	learn: 0.3560078	total: 11.5s	remaining: 5.81s
665:	learn: 0.3559399	total: 11.6s	remaining: 5.79s
666:	learn: 0.3559390	total: 11.6s	remaining: 5.77s
667:	learn: 0.3557782	total: 11.6s	remaining: 5.76s
668:	learn: 0.3557710	total: 11.6s	remaining: 5.74s
669:	learn: 0.3557284	total: 11.6s	remaining: 5.72s
670:	learn: 0.3555382	total: 11.6s	remaining: 5.7s
671:	learn: 0.3555271	total: 11.6s	remaining: 5.68s
672:	learn: 0.3554502	total: 11.7s	remaining: 5.67s
673:	learn: 0.3552826	total: 11.7s	remaining: 5.65s
674:	learn: 0.3552747	total: 11.7s	remaining: 5.63s
675:	learn: 0.3551307	total: 11.7s	remaining: 5.61s
676:	learn: 0.3550750	total: 11.7s	remaining: 5.6s
677:	learn: 0.3548857	total: 11.8s	remaining: 5.58s
678:	learn: 0.3547020	total: 11.8s	remaining: 5.56s
679:	learn: 0.

827:	learn: 0.3437342	total: 14.5s	remaining: 3s
828:	learn: 0.3436846	total: 14.5s	remaining: 2.99s
829:	learn: 0.3436284	total: 14.5s	remaining: 2.97s
830:	learn: 0.3435728	total: 14.5s	remaining: 2.95s
831:	learn: 0.3435687	total: 14.5s	remaining: 2.93s
832:	learn: 0.3435329	total: 14.6s	remaining: 2.92s
833:	learn: 0.3432537	total: 14.6s	remaining: 2.9s
834:	learn: 0.3432475	total: 14.6s	remaining: 2.88s
835:	learn: 0.3432224	total: 14.6s	remaining: 2.87s
836:	learn: 0.3431962	total: 14.6s	remaining: 2.85s
837:	learn: 0.3431869	total: 14.7s	remaining: 2.83s
838:	learn: 0.3431828	total: 14.7s	remaining: 2.81s
839:	learn: 0.3430936	total: 14.7s	remaining: 2.8s
840:	learn: 0.3430177	total: 14.7s	remaining: 2.78s
841:	learn: 0.3429793	total: 14.7s	remaining: 2.76s
842:	learn: 0.3429576	total: 14.7s	remaining: 2.75s
843:	learn: 0.3429184	total: 14.8s	remaining: 2.73s
844:	learn: 0.3428957	total: 14.8s	remaining: 2.71s
845:	learn: 0.3428636	total: 14.8s	remaining: 2.69s
846:	learn: 0.342

986:	learn: 0.3342411	total: 17.5s	remaining: 230ms
987:	learn: 0.3342280	total: 17.5s	remaining: 213ms
988:	learn: 0.3341445	total: 17.5s	remaining: 195ms
989:	learn: 0.3339434	total: 17.6s	remaining: 177ms
990:	learn: 0.3339399	total: 17.6s	remaining: 160ms
991:	learn: 0.3338529	total: 17.6s	remaining: 142ms
992:	learn: 0.3338480	total: 17.6s	remaining: 124ms
993:	learn: 0.3337947	total: 17.6s	remaining: 106ms
994:	learn: 0.3336606	total: 17.6s	remaining: 88.7ms
995:	learn: 0.3335693	total: 17.7s	remaining: 70.9ms
996:	learn: 0.3335467	total: 17.7s	remaining: 53.2ms
997:	learn: 0.3335223	total: 17.7s	remaining: 35.5ms
998:	learn: 0.3335153	total: 17.7s	remaining: 17.7ms
999:	learn: 0.3334005	total: 17.7s	remaining: 0us


In [22]:
y_test_cat = modelCatBoost.predict(x_test_cat)
y_test_cat

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [24]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': y_test_cat})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!
